apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-tz3y
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-tz3y@sha256:39fa1da9e82b41952f6fc23c983ad64f76a67bd8e283154b9bffa61c291a1b2f
        name: my-nodejs
        resources: {}
status: {}
